### ISSUE TITLE
Already supported natively in the webui -- add notice to readme/extension

### ISSUE THREAD

**Issue by catboxanon** [hako-mikan/sd-webui-prevent-artifact#1]
I think there should be some form of notice in the extension code, or at minimum in the readme, since this functionality is now implemented natively via https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/14874 and https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/e2b19900ec37ef517d8175a7d86c1925ca9f9e91 in the `dev` branch, and now the [upcoming 1.8.0 version](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.8.0-RC)

It would also limit the amount of issues created like this one: https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/420

**Comment by hako-mikan** [comment]
Note added. Thanks.
