### ISSUE TITLE
Not working with Forge anymore

### ISSUE THREAD

**Issue by Bullseye110** [hako-mikan/sd-webui-prevent-artifact#3]
Hello!
The extension is not working with the newest version of Forge. Is there any fix for this?
This extension is very useful for generating good images with Pony/XL models...
Thanks!

This is the error it gives:
*** Error loading script: pa.py
    Traceback (most recent call last):
      File "/kaggle/working/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/kaggle/working/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/kaggle/working/stable-diffusion-webui-forge/extensions/sd-webui-prevent-artifact/scripts/pa.py", line 55, in <module>
        sd_hijack_clip.FrozenCLIPEmbedderWithCustomWordsBase.process_tokens = process_tokens
    AttributeError: module 'modules.sd_hijack_clip' has no attribute 'FrozenCLIPEmbedderWithCustomWordsBase'

**Comment by hako-mikan** [comment]
This script is meant to be used until the main application obtains the same functionality. 
At this point, the main Forge application already has similar features, so I recommend using that instead.
Emphasis mode (for Forge) Setting these to "No norm" will achieve the same effect as activating this extension.

**Comment by Bullseye110** [comment]
> This script is meant to be used until the main application obtains the same functionality. At this point, the main Forge application already has similar features, so I recommend using that instead. Emphasis mode (for Forge) Setting these to "No norm" will achieve the same effect as activating this extension.

Alright, I didn't know that, thanks for this, will try and leave feedback!
Afterwards I'll close the issue!

**Comment by Bullseye110** [comment]
> This script is meant to be used until the main application obtains the same functionality. At this point, the main Forge application already has similar features, so I recommend using that instead. Emphasis mode (for Forge) Setting these to "No norm" will achieve the same effect as activating this extension.

Your solution worked!
Thank you and I really appreciate!
